import os
import sys


# Add project root to path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from app import create_app
from app.core.extensions import db

def generate_dbml():
    """
    Generates DBML content from SQLAlchemy metadata.
    """
    app = create_app()
    
    with app.app_context():
        # Load models
        from app.core import models # noqa

        metadata = db.metadata
        
        print("// DBML generated by Personal-Guru script")
        print(f"// Generated at: {os.popen('date').read().strip()}")
        print("")

        # 1. Tables
        for table_name, table in metadata.tables.items():
            print(f"Table {table_name} {{")
            for column in table.columns:
                col_str = f"  {column.name} {column.type}"
                
                settings = []
                if column.primary_key:
                    settings.append("pk")
                if not column.nullable: # In DBML, not null is default implies? No, usually explicitly "not null"
                    settings.append("not null") 
                if column.unique:
                    settings.append("unique")
                if column.default:
                    # simplistic default handling
                    arg = column.default.arg
                    if not callable(arg):
                         settings.append(f"default: `{arg}`")
                
                if settings:
                    col_str += f" [{', '.join(settings)}]"
                
                print(col_str)
            print("}")
            print("")

        # 2. Relationships (Foreign Keys)
        for table_name, table in metadata.tables.items():
            for column in table.columns:
                for fk in column.foreign_keys:
                    # fk.target_fullname is usually 'table.column'
                    target_table, target_col = fk.target_fullname.split('.')
                    # DBML Syntax: Ref: tables.user_id > users.id
                    print(f"Ref: {table_name}.{column.name} > {target_table}.{target_col}")

if __name__ == "__main__":
    generate_dbml()